.TH UMXTRV "September 22, 2018"
.SH NAME
UNXTRV - extract files in a XTRV archive

.SH DESCRIPTION
unxtrv is an extracting program designed to extract files archived using xtrv(1).

.SH USAGE

run unxtrv and provide archive you want to extract as argument
it will do the rest:
.br
unxtrv file.xtrv
.br
for key protected files use -k to provide a key:
.br
unxtrv -k secretkey file.xtrv

.SH SEE ALSO
xtrv(1)

.SH AUTHOR
Copyright 2018 - Tshildzi Tshivhula
